In [1]:
import pandas as pd
#titanic dataset
df=pd.read_csv('https://gist.githubusercontent.com/jwalsh/ce1dc0436aba5b7a5c9666f47fa5a380/raw/5ce3854392b43ff97907112d344fc008229b0445/titanic.csv')

In [5]:
df.head(6)

PassengerId  Survived  Pclass      Lname  \
0            1         0       3     Braund   
1            2         1       1    Cumings   
2            3         1       3  Heikkinen   
3            4         1       1   Futrelle   
4            5         0       3      Allen   
5            6         0       3      Moran   

                                          Name     Sex   Age  SibSp  Parch  \
0                              Mr. Owen Harris    male  22.0      1      0   
1   Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1      0   
2                                  Miss. Laina  female  26.0      0      0   
3           Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
4                            Mr. William Henry    male  35.0      0      0   
5                                    Mr. James    male   NaN      0      0   

             Ticket     Fare Cabin Embarked  
0         A/5 21171   7.2500   NaN        S  
1          PC 17599  71.2833   C85        C  
2  STON/O2. 3101282   7.9250   NaN        S  
3            113803  53.1000  C123        S  
4            373450   8.0500   NaN        S  
5            330877   8.4583   NaN        Q

In [ ]:
df.describe()  #it will only render for the columns having numerical values

In [ ]:
df.columns

# Now how to use describe for categorical variables

In [ ]:
df.dtypes

In [ ]:
df.dtypes == 'object'

In [ ]:
categorical_data = df.dtypes[df.dtypes == 'object']
categorical_data

In [ ]:
categorical=df.dtypes[df.dtypes == 'object'].index
df[categorical]

In [ ]:
df[categorical].describe()

In [ ]:
df['Name'][0:12]  #as series are like lists

In [ ]:
df['Cabin'].isnull()==True

In [ ]:
df[df['Cabin'].isnull()]

In [ ]:
df[df['Ticket']==max(df['Ticket'])]

In [ ]:
len(df[df['Sex']=='male'])

In [ ]:
len(df[df['Sex']=='female'])

# value_counts is used to count the number of values present unique in Sex coloumn means how many male and then how many female are present

In [ ]:
df['Sex'].value_counts()[0]

In [ ]:
df['Sex'].value_counts()

In [ ]:
len(df[df['Survived']== 1])

In [ ]:
len(df[df['Survived']== 0])

In [ ]:
df[df['Age']== max(df['Age'])]['Name']

In [ ]:
df

In [ ]:
df['Name'].str[:1]=='Mr.'

In [ ]:
d11= df[df['Age']<40]
d11

In [ ]:
df[(df['Survived']==0) & (df['Age']<40)]

In [ ]:
df['Cabin'].isnull()

# replace characters and numberic data from Cabin column

In [ ]:
df['Cabin'].str.replace('[A-Z]',' ')

In [ ]:
df['Cabin']

# Read all resume from ineuron git in pdf, word and try to create a dataframe with resume name as a index value and in column i am expecting email id

# linked in ID, git id , skills as a result

In [2]:
pip install python-docx

     ---------------------------------------- 5.6/5.6 MB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for python-docx: filename=python_docx-0.8.11-py3-none-any.whl size=184489 sha256=dc4a6931bf4d8faeda15affacd2a763cfe4ae7c4b311f0b6ec0a89b2075e011a
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\83\8b\7c\09ae60c42c7ba4ed2dddaf2b8b9186cb105255856d6ed3dba5
Successfully built python-docx
Note: you may need to restart the kernel to use updated packages.


In [2]:
import docx
import io

In [3]:
content=docx.Document(r'C:\Users\user\Desktop\python\12+.docx').paragraphs[0].text

In [4]:
content

''

In [6]:
df.dropna()  ##df.fillna(df['Age'].mean())

PassengerId  Survived  Pclass        Lname  \
1              2         1       1      Cumings   
3              4         1       1     Futrelle   
6              7         0       1     McCarthy   
10            11         1       3    Sandstrom   
11            12         1       1      Bonnell   
21            22         1       2      Beesley   
23            24         1       1       Sloper   
27            28         0       1      Fortune   
52            53         1       1       Harper   
54            55         0       1        Ostby   
62            63         0       1       Harris   
66            67         1       2          Nye   
75            76         0       3         Moen   
88            89         1       1      Fortune   
92            93         0       1      Chaffee   
96            97         0       1  Goldschmidt   
97            98         1       1   Greenfield   
102          103         0       1        White   
110          111         0       1       Porter   
118          119         0       1       Baxter   
123          124         1       2       Webber   
124          125         0       1        White   
136          137         1       1       Newsom   
137          138         0       1     Futrelle   
139          140         0       1       Giglio   
148          149         0       2     Navratil   
151          152         1       1        Pears   

                                            Name     Sex   Age  SibSp  Parch  \
1     Mrs. John Bradley (Florence Briggs Thayer)  female  38.0      1      0   
3             Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0   
6                                  Mr. Timothy J    male  54.0      0      0   
10                          Miss. Marguerite Rut  female   4.0      1      1   
11                               Miss. Elizabeth  female  58.0      0      0   
21                                  Mr. Lawrence    male  34.0      0      0   
23                          Mr. William Thompson    male  28.0      0      0   
27                         Mr. Charles Alexander    male  19.0      3      2   
52              Mrs. Henry Sleeper (Myna Haxtun)  female  49.0      1      0   
54                       Mr. Engelhart Cornelius    male  65.0      0      1   
62                           Mr. Henry Birkhardt    male  45.0      1      0   
66                       Mrs. (Elizabeth Ramell)  female  29.0      0      0   
75                             Mr. Sigurd Hansen    male  25.0      0      0   
88                             Miss. Mabel Helen  female  23.0      3      2   
92                            Mr. Herbert Fuller    male  46.0      1      0   
96                                  Mr. George B    male  71.0      0      0   
97                           Mr. William Bertram    male  23.0      0      1   
102                           Mr. Richard Frasar    male  21.0      0      1   
110                       Mr. Walter Chamberlain    male  47.0      0      0   
118                             Mr. Quigg Edmond    male  24.0      0      1   
123                                  Miss. Susan  female  32.5      0      0   
124                         Mr. Percival Wayland    male  54.0      0      1   
136                         Miss. Helen Monypeny  female  19.0      0      2   
137                            Mr. Jacques Heath    male  37.0      1      0   
139                                   Mr. Victor    male  24.0      0      0   
148                                   Mr. Michel    male  36.5      0      2   
151                   Mrs. Thomas (Edith Wearne)  female  22.0      1      0   

          Ticket      Fare        Cabin Embarked  
1       PC 17599   71.2833          C85        C  
3         113803   53.1000         C123        S  
6          17463   51.8625          E46        S  
10       PP 9549   16.7000           G6        S  
11        113783   26.5500         C103        S  
21        248698   13.0000   

In [13]:
df.groupby('Embarked').describe().T

Embarked                    C           Q           S
PassengerId count   32.000000   13.000000  110.000000
            mean    75.781250   63.769231   81.181818
            std     45.033131   46.547742   45.268451
            min      2.000000    6.000000    1.000000
            25%     39.250000   29.000000   43.000000
            50%     63.000000   47.000000   84.500000
            75%    120.000000  110.000000  117.500000
            max    156.000000  144.000000  155.000000
Survived    count   32.000000   13.000000  110.000000
            mean     0.375000    0.538462    0.309091
            std      0.491869    0.518875    0.464234
            min      0.000000    0.000000    0.000000
            25%      0.000000    0.000000    0.000000
            50%      0.000000    1.000000    0.000000
            75%      1.000000    1.000000    1.000000
            max      1.000000    1.000000    1.000000
Pclass      count   32.000000   13.000000  110.000000
            mean     2.125000    3.000000    2.454545
            std      0.941858    0.000000    0.749757
            min      1.000000    3.000000    1.000000
            25%      1.000000    3.000000    2.000000
            50%      2.500000    3.000000    3.000000
            75%      3.000000    3.000000    3.000000
            max      3.000000    3.000000    3.000000
Age         count   22.000000    5.000000   98.000000
            mean    29.659091   25.100000   27.855408
            std     17.064574   26.321094   13.472829
            min      3.000000    2.000000    0.830000
            25%     18.250000   15.000000   20.000000
            50%     25.000000   19.000000   26.500000
            75%     36.750000   19.000000   35.000000
            max     71.000000   70.500000   66.000000
SibSp       count   32.000000   13.000000  110.000000
            mean     0.468750    0.461538    0.681818
            std      0.567074    1.126601    1.156805
            min      0.000000    0.000000    0.000000
            25%      0.000000    0.000000    0.000000
            50%      0.000000    0.000000    0.000000
            75%      1.000000    0.000000    1.000000
            max      2.000000    4.000000    5.000000
Parch       count   32.000000   13.000000  110.000000
            mean     0.312500    0.076923    0.463636
            std      0.592289    0.277350    0.973759
            min      0.000000    0.000000    0.000000
            25%      0.000000    0.000000    0.000000
            50%      0.000000    0.000000    0.000000
            75%      0.250000    0.000000    0.000000
            max      2.000000    1.000000    5.000000
Fare        count   32.000000   13.000000  110.000000
            mean    40.291013   11.273723   26.083862
            std     49.385066    7.223292   37.443517
            min      7.225000    6.750000    6.975000
            25%     11.241700    7.750000    8.050000
            50%     22.018750    7.879200   13.000000
            75%     61.529200    8.458300   28.725000
            max    247.520800   29.125000  263.000000

# df.iloc[row_integer,column_integer]

In [17]:
df.iloc[[2,3],3]

2    Heikkinen
3     Futrelle
Name: Lname, dtype: object

# numpy stands for numerical python used to create data in form of array and matrix

In [4]:
df1= pd.DataFrame({'job1':'engineer','phone':'983449648' , 'SEX':'male'})
df1

ValueError: If using all scalar values, you must pass an index

In [6]:
df2= pd.DataFrame({'job1':['engineer'],'phone':[983449648] , 'SEX':['male']})
df2

job1      phone   SEX
0  engineer  983449648  male

# Make new columns by the use of existing coloumns in pandas

In [20]:
df2['income']= int(df2['phone'])*0.5

In [21]:
df2

job1      phone   SEX       income
0  engineer  983449648  male  491724824.0

In [22]:
def test(a):
    return a*0.5

In [24]:
df2['income_generated_thorugh_function']= df2['phone'].apply(test)
df2

job1      phone   SEX       income  income_generated_thorugh_function
0  engineer  983449648  male  491724824.0                        491724824.0

In [26]:
def test1(s):
    return s[::-1]

In [27]:
df2['new_col']= df2['job1'].apply(test1)
df2

job1      phone   SEX       income  income_generated_thorugh_function  \
0  engineer  983449648  male  491724824.0                        491724824.0   

    new_col  
0  reenigne

In [29]:
df2['length_new_col']=df2['new_col'].apply(len)
df2

job1      phone   SEX       income  income_generated_thorugh_function  \
0  engineer  983449648  male  491724824.0                        491724824.0   

    new_col  col2  length_new_col  
0  reenigne     8               8

In [71]:
df2['lambda_col']=df2['SEX'].apply(lambda x:x[0:2])
df2

job1      phone   SEX       income  income_generated_thorugh_function  \
0  engineer  983449648  male  491724824.0                        491724824.0   

    new_col  col2  length_new_col lambda_col  
0  reenigne     8               8         ma

# NUMPY

In [30]:
import numpy as np

l=[1,2,3,4]
numpy_array = np.array(l)
numpy_array

array([1, 2, 3, 4])

In [31]:
numpy_matrix=np.mat(l)
numpy_matrix

matrix([[1, 2, 3, 4]])

In [32]:
a= np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [34]:
b=np.array([2,3,4,5],ndmin=3)  ##dimensional
b

array([[[2, 3, 4, 5]]])

In [49]:
arr = np.random.rand(3,4)  ##generate a random 3 cross 4 matrix of random values
arr

array([[0.47396375, 0.52249423, 0.05178235, 0.0856605 ],
       [0.60366681, 0.75553104, 0.15561657, 0.77053242],
       [0.33804925, 0.89910175, 0.74483841, 0.87631547]])

In [50]:
arr[2,3]

0.8763154664650394

In [55]:
arr[[1,2] ,[2,3]]

array([0.15561657, 0.87631547])

In [56]:
arr[0:2 , [1,3]]

array([[0.52249423, 0.0856605 ],
       [0.75553104, 0.77053242]])

In [47]:
np.random.randint(6)

4

In [58]:
np.arange(2,4,0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8])

# Multiplication in numpy using @ symbol

In [63]:
a = np.array([[1,2] ,[3,4]])
print(type(a))
b = np.array([[2,3] , [4,5]])

<class 'numpy.ndarray'>


In [60]:
m = a@b  ##multiplication
m

array([[10, 13],
       [22, 29]])

# Generation of random array using lambda functions

In [64]:
c= np.fromfunction(lambda i,j:i*j , (2,4), dtype='int')  ##2 dimesional array of 2 cross 4 form
c

array([[0, 0, 0, 0],
       [0, 1, 2, 3]])

In [65]:
df3= pd.DataFrame(c)
df3

0  1  2  3
0  0  0  0  0
1  0  1  2  3

In [69]:
c1= np.fromfunction(lambda i,j,k:i*j*k , (3,2,3),dtype='int')  ##generate (3,2,3) 3 dimensional array of 2 cross 3 form
c1

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 1, 2]],

       [[0, 0, 0],
        [0, 2, 4]]])

In [70]:
df4=pd.DataFrame(c1)  ##you cannot create dataframe from 3 dimensional array 
df4

ValueError: Must pass 2-d input. shape=(3, 2, 3)

In [1]:
import numpy as np

In [2]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [3]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.linspace(3,4,5, retstep=True) ##need 5 numbers from 3 to 4 range 

(array([3.  , 3.25, 3.5 , 3.75, 4.  ]), 0.25)

In [13]:
np.logspace(3,4,10 ,base=10) 

array([ 1000.        ,  1291.54966501,  1668.1005372 ,  2154.43469003,
        2782.55940221,  3593.8136638 ,  4641.58883361,  5994.84250319,
        7742.63682681, 10000.        ])

# arange function in numpy, it is similar to range function in python but in range function in python you cannot provide decimal step but in numpy with arange function you can provide decimal step

In [24]:
a= np.arange(2.8,10,0.2)
a

array([2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2,
       5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8,
       8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [25]:
a= np.arange(2.8,10,0.2).reshape(6,4)
a

ValueError: cannot reshape array of size 36 into shape (6,4)

In [30]:
a= np.arange(2.8,10,0.2).reshape(6,-9)  ##in reshape you just put one correct element in row or coloumn and for other if you put negative it will itself take or find the other number which will complete the matrix like in this case it's 6 so you do not have to write 6
a

array([[2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. ],
       [5.2, 5.4, 5.6, 5.8, 6. , 6.2],
       [6.4, 6.6, 6.8, 7. , 7.2, 7.4],
       [7.6, 7.8, 8. , 8.2, 8.4, 8.6],
       [8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [31]:
a= np.arange(2.8,10,0.2).reshape(6,6)
a

array([[2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. ],
       [5.2, 5.4, 5.6, 5.8, 6. , 6.2],
       [6.4, 6.6, 6.8, 7. , 7.2, 7.4],
       [7.6, 7.8, 8. , 8.2, 8.4, 8.6],
       [8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [27]:
a.max(axis=1)

array([3.8, 5. , 6.2, 7.4, 8.6, 9.8])

In [28]:
a.max(axis=0)

array([8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [35]:
l=[1,2,3,4,5,6]
b=np.array(l)

In [36]:
b

array([1, 2, 3, 4, 5, 6])

In [37]:
b+a

array([[ 3.8,  5. ,  6.2,  7.4,  8.6,  9.8],
       [ 5. ,  6.2,  7.4,  8.6,  9.8, 11. ],
       [ 6.2,  7.4,  8.6,  9.8, 11. , 12.2],
       [ 7.4,  8.6,  9.8, 11. , 12.2, 13.4],
       [ 8.6,  9.8, 11. , 12.2, 13.4, 14.6],
       [ 9.8, 11. , 12.2, 13.4, 14.6, 15.8]])

In [38]:
b.T+a  ##for both cases it is giving same result because of 1d nature of b , so if you want to add column vise you should convert b into 2d first

array([[ 3.8,  5. ,  6.2,  7.4,  8.6,  9.8],
       [ 5. ,  6.2,  7.4,  8.6,  9.8, 11. ],
       [ 6.2,  7.4,  8.6,  9.8, 11. , 12.2],
       [ 7.4,  8.6,  9.8, 11. , 12.2, 13.4],
       [ 8.6,  9.8, 11. , 12.2, 13.4, 14.6],
       [ 9.8, 11. , 12.2, 13.4, 14.6, 15.8]])

In [47]:
a

array([[2.8, 3. , 3.2, 3.4, 3.6, 3.8],
       [4. , 4.2, 4.4, 4.6, 4.8, 5. ],
       [5.2, 5.4, 5.6, 5.8, 6. , 6.2],
       [6.4, 6.6, 6.8, 7. , 7.2, 7.4],
       [7.6, 7.8, 8. , 8.2, 8.4, 8.6],
       [8.8, 9. , 9.2, 9.4, 9.6, 9.8]])

In [52]:
b=b.reshape(1,-1)  ##convert it to 2d first then do its transpose the add to a
b

array([[1, 2, 3, 4, 5, 6]])

In [53]:
b.T+a

array([[ 3.8,  4. ,  4.2,  4.4,  4.6,  4.8],
       [ 6. ,  6.2,  6.4,  6.6,  6.8,  7. ],
       [ 8.2,  8.4,  8.6,  8.8,  9. ,  9.2],
       [10.4, 10.6, 10.8, 11. , 11.2, 11.4],
       [12.6, 12.8, 13. , 13.2, 13.4, 13.6],
       [14.8, 15. , 15.2, 15.4, 15.6, 15.8]])

In [45]:
np.sqrt(a)

array([[1.67332005, 1.73205081, 1.78885438, 1.84390889, 1.8973666 ,
        1.94935887],
       [2.        , 2.04939015, 2.0976177 , 2.14476106, 2.19089023,
        2.23606798],
       [2.28035085, 2.32379001, 2.36643191, 2.40831892, 2.44948974,
        2.48997992],
       [2.52982213, 2.56904652, 2.60768096, 2.64575131, 2.68328157,
        2.7202941 ],
       [2.75680975, 2.79284801, 2.82842712, 2.86356421, 2.89827535,
        2.93257566],
       [2.96647939, 3.        , 3.03315018, 3.06594194, 3.09838668,
        3.13049517]])

# Shallow and deep copy in numpy

In [54]:
x=[1,2,3,4]
y=x ##shallow copy

y[0]=2
print(x)

[2, 2, 3, 4]


In [60]:
x=[1,2,3,4]
y=x ##shallow copy

y[0]=2

z=np.copy(x) ##deep copy will ot change x value if z values are changed
z[0]=5
print("x",x)
print("z",z)

x [2, 2, 3, 4]
z [5 2 3 4]


In [58]:
id(x)

2209927866560

In [59]:
id(z)

2209949030992

In [61]:
id(y)

2209949042816